### PR TITLE
Updates  : keys -> ans

### PR DESCRIPTION
**Pull request by RounabhSahu**
keys is a function for javascript which is giving error in some browsers

### CODE REVIEW

**Comment by sauravhathi** [comment]
Which browser do you use?

**Comment by RounabhSahu** [comment]
I use Firefox and edge . I didn't try in chrome

**Review by sauravhathi — APPROVED** [review]

**Comment by sauravhathi** [comment]
Yes, the keys() function is a method in JavaScript that returns an array of a given object's own enumerable property names, in the same order as we get with a normal loop.

**Comment by RounabhSahu** [comment]
Thanks!

**Pull request merged**
